sudo: false
dist: xenial
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache
notifications:
  email: true
node_js:
  - "12"
  - "10"
  - "8"
env:
  global:
    - TEST_SITE=travis-ci
script:
  - yarn run test-ci
  - yarn run build
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash <(curl -s https://codecov.io/bash); fi
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then npm run semantic-release; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
