sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.mongodb-binaries
notifications:
  email: true
node_js:
  - "9"
  - "8"
script:
  - yarn run test
  - yarn run build
after_success:
  - bash <(curl -s https://codecov.io/bash)
